let products = [
    "Sukker",
    "Hvedemel",
    "Kærgården",
    "Shampoo",
    "Balsam",
    "Håndsæbe",
    "Corn flakes",
    "Letmærk",
    "Coca Cola",
    "Fanta",
    "Smøger",
    "Vodka",
    "Hakket oksekød",
    "Færdigretter",
    "Stegemargarine",
    "Kondomer",
    "Ugeblade",
    "Captain Morgan",
    "Chokolade",
    "Boljser",
    "Lakrids",
    "Vingummi",
    "Sødmælk",
    "Skummelmælk",
    "Kaffe",
    "Juice",
    "Bananer",
    "Æbler",
    "Appelsin",
    "Jordbær",
];

let categories = [
    "Frostvarer",
    "Kolonial",
    "Slik",
    "Drikkevarer",
    "Frugt & Grønt",
    "Kølevarer & Mejeri",
    "Husholdning",
    "Personlig Pleje",
];

let prices = [
    "1-5 kr.",
    "6-10 kr.",
    "11-15 kr.",
    "16-20 kr.",
    "21-25 kr.",
    "26-30 kr.",
    "31-35 kr.",
    "36-40 kr.",
    "41-45 kr.",
    "46-50 kr.",
];

